
package client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-08-18T13:15:56.210+08:00
 * Generated source version: 3.3.7
 *
 */
public final class HelloWorld_HelloWorldPort_Client {

    private static final QName SERVICE_NAME = new QName("http://example/", "HelloWorldService");

    private HelloWorld_HelloWorldPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = HelloWorldService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        HelloWorldService ss = new HelloWorldService(wsdlURL, SERVICE_NAME);
        HelloWorld port = ss.getHelloWorldPort();

        {
        System.out.println("Invoking sayHelloWorldFrom...");
        java.lang.String _sayHelloWorldFrom_arg0 = "";
        java.lang.String _sayHelloWorldFrom__return = port.sayHelloWorldFrom(_sayHelloWorldFrom_arg0);
        System.out.println("sayHelloWorldFrom.result=" + _sayHelloWorldFrom__return);


        }

        System.exit(0);
    }

}
