
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-08-18T13:15:56.235+08:00
 * Generated source version: 3.3.7
 *
 */

@javax.jws.WebService(
                      serviceName = "HelloWorldService",
                      portName = "HelloWorldPort",
                      targetNamespace = "http://example/",
                      // wsdlLocation = "file:/E:/ChromeDownload/HelloWorld.wsdl",
                      endpointInterface = "client.HelloWorld")

public class HelloWorldPortImpl implements HelloWorld {

    private static final Logger LOG = Logger.getLogger(HelloWorldPortImpl.class.getName());

    /* (non-Javadoc)
     * @see client.HelloWorld#sayHelloWorldFrom(java.lang.String arg0)*
     */
    public java.lang.String sayHelloWorldFrom(java.lang.String arg0) {
        LOG.info("Executing operation sayHelloWorldFrom");
        System.out.println(arg0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
