package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-08-18T13:15:56.251+08:00
 * Generated source version: 3.3.7
 *
 */
@WebService(targetNamespace = "http://example/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebMethod
    @Action(input = "http://example/HelloWorld/sayHelloWorldFromRequest", output = "http://example/HelloWorld/sayHelloWorldFromResponse")
    @RequestWrapper(localName = "sayHelloWorldFrom", targetNamespace = "http://example/", className = "client.SayHelloWorldFrom")
    @ResponseWrapper(localName = "sayHelloWorldFromResponse", targetNamespace = "http://example/", className = "client.SayHelloWorldFromResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayHelloWorldFrom(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
