
package client;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-08-18T13:15:56.259+08:00
 * Generated source version: 3.3.7
 *
 */

public class HelloWorld_HelloWorldPort_Server{

    protected HelloWorld_HelloWorldPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new HelloWorldPortImpl();
        String address = "http://localhost:9000/HelloWorld";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new HelloWorld_HelloWorldPort_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
